export const TRANSLATIONS = {
    en_US: {
      Username: 'Username',
      Password: 'Password',
      Forgot_password: 'Forgot password?',
      Sign_in: 'Sign in',
      Search:'Search',
      Products:'Products',
      Add_Product:'ADD PRODUCT',
      Dashboard:'Dashboard',
      Sales_Order:'Sales Order',
      Purchase_Order:'Purchase Order',
      Supplier:'Supplier',
      Customer:'Customer',
      Product_Group:'Product Group',
      Sales_Unit:'Sales Unit',
      Kilogram:'Kilogram',
      Product:'Product',
      Productcode:'Productcode',
      Previous:'Previous',
      Next:'Next',
      Show_entries:'Show entries',
      Show:'Show',
      Entries:'entries',
      Show_page:'Showing page',
      Producttype: 'Producttype',
      Concentration: 'Concentration',
      Addition: 'Addition',
      Description: 'Description',
      Salesunit: 'Salesunit',
      Partial: 'Partial',
      Intrastat: 'Intrastat',
      Save: 'Save',
      User: 'User',
      Add_User: 'Add User',
      FirstName: 'FirstName',
      LastName: 'LastName',
      Email: 'Email',
      Active: 'Active',
      State: 'State',
      View_User: 'View User',
      Edit_User: 'Edit User',
      UserName: 'UserName',
      Roles: 'Roles',
      ConfirmPassword: 'ConfirmPassword',
      PhoneNumber: 'PhoneNumber',
      IsActive: 'IsActive',
      Product_Details: 'Product Details',
      Productgroup: 'Productgroup',
      Purchase_Price: 'Purchase Price',
      Price: 'Price',
      Start_date: 'Start date',
      End_date: 'End date',
      Add_Purchase_Price: 'Add Purchase Price',
      Sales_Price: 'Sales Price',
      Add_Salese_Price: 'Add Salese Price',
      Transport_Price: 'Transport Price',
      Id: 'Id',
      Transporter: 'Transporter',
      Pricingtype: 'Pricingtype',
      Add_Transport_Price: 'Add Transport Price',
      Add_Sales_Order: 'Add Sales Order',
      Reference: 'Reference',
      Order_Date: 'Order Date',
      Total_amount: 'Total amount',
      Sales_Order_Details: 'Sales Order Details',
      Loading_Date: 'Loading Date',
      Quantity: 'Quantity',
      Amount: 'Amount',
      Add_Pursase_Order: 'Add Pursase Order',
      Invoice: 'Invoice',
      Invoice_date: 'Invoice date',
      Journal: 'Journal',
      Expiration_Date: 'Expiration Date',
      Purchase_Order_Details: 'Purchase Order Details',
      Add_row: 'Add row',
      GlCode: 'GlCode',
      VATCode: 'VATCode',
      VATAmount: 'VATAmount',
      Reporting_Date: 'Reporting Date',
      Purchase_Unit: 'Purchase Unit',
      Approver: 'Approver',
      Add_Price: 'Add Price',
      Copy_Product: 'Copy Product',
      Tasks: 'Tasks',
      Add_Tasks: 'Add Tasks',
      Creat_Task: 'Creat Task',
      Task_Type: 'Task Type',
      Employee: 'Employee',
      Deadline: 'Deadline',
      Subject: 'Subject',
      CustomerName: 'CustomerName',
      DateCreated: 'DateCreated',
      CreateBy: 'CreateBy',
      Address: 'Address',
      Postcode: 'Postcode',
      City: 'City',
      Country: 'Country',
      Action: 'Action',
      Codex_SAS:'Codex SAS',
      Extra_information: 'Extra_information',
      Financial: 'Financial',
      Location: 'Location',
      Telephone: 'Telephone',
      E_mail: 'E-mail',
      Website: 'Website',
      Turnover_current_year: 'Turnover current year',
      Turnover_last_year: 'Turnover last year',
      Revenue_for_the_year: 'Revenue for the year',
      Progress: 'Progress',
      Payment_term: 'Payment term',
      days: 'days',
      Contacts: 'Contacts',
      Telephone_work: 'Telephone work',
      Mobile: 'Mobile',
      Status: 'Status',
      All_contacts: 'All Contacts',
      Add_contacts: 'Add Contacts',
      Models: 'Models',
      Model: 'Model',
      Type: 'Type',
      Size: 'Size',
      Articles: 'Articles',
      Item_Type: 'Itemtype',
      Color: 'Color',
      Length: 'Length',
      Orders: 'Orders',
      Ordernumber: 'Ordernumber',
      Orderdate: 'Orderdate',
      Deliverydate: 'Deliverydate',
      Customer_ordernumber: 'Customer ordernumber',
      Item: 'Item',
      Discount: 'Discount',
      CustomerItemNumber: 'CustomerItemNumber',
      Unit: 'Unit',
      Number: 'Number',
      Order_detail: 'Order Detail',
      Competitor_models: 'Competitor Model',
      Revenue: 'Revenue',
      Price_agreements: 'Price Agreements',
      Upon_purchase: 'Upon Purchase',
      Price_per: 'Price per',
      Show_rate: 'Show Rate',
      Rate: 'Rate',
      Quotations: 'Quotations',
      Quotation_Number: 'QuotationNumber',
      Delivery: 'Delivery',
      Approved: 'Approved',
      Date: 'Date',
      Not_Approved: 'Not Approved',
      Quote_detail: 'Quote_detail',
      Mold: 'Mold',
      Article_Number: 'Article Number',
      Visit_report: 'VisitReport',
      Add_VisitReport: 'Add Visit Report',
      Create_a_new_report: 'Create a new report',
      Visit_Date: 'Visit Date',
      Further: 'Further',
      existing_or_potential_customer: 'Existing or potential customer',
      Select_answer: 'Select answer',
      Remarks: 'Remarks',
      Select: 'Select...',
      CreatedBy: 'CreatedBy',
      Submit: 'Submit',
      Visit_reports_page: 'Visit report page',
      Customers_page: 'Customer page',
      Number_Of_Tasks: 'Number Of Tasks',
      Nearest_Customers: 'Nearest_Customers',
      dashboard_page_customer_near_by_km: 'dashboard/page.customer_near_by_km',
      Select_Customer: 'Select customer',
      map_lang: 'EN',
      Create_Customer: 'Create Customer',
      Customer_City: 'CustomerCity',
      Note: 'Note',
      Add_Customer: 'Add Customer',
      Create_Contact: 'Create Contact',
      Phone_Work: 'Phone Work',
      Phone: 'Phone',
      Name: 'Name',
      Zipcode: 'Zipcode',
      Edit_Customer: 'Edit Customer',
      Edit_Contact: 'Edit Contact',
      Edit_Task: 'Edit Task',
      Edit_Report: 'Edit Vist Report',
      Task_history: 'Task Hitory',
      PreviousEmployee: 'PreviousEmployee',
      NewEmployee: 'NewEmployee',
      ChangeDate: 'ChangeDate',
      Top_Customers: 'Top 10 Customers',
      Top_Items: 'Top 10 Items',
      Top_Models: 'Top 10 Models',
      Answer_visit_report: 'Answer Visit Report',
      Question: 'Question',
      Answer: 'Answer',
      Attachment: 'Attachment',
      Choose_File: "Choose File",
      View: 'View',
      Documents: 'Documents',
      DocumentId: 'DocumentId',
      Task: 'Task',
      Success: 'Success!',
      Fail: 'Fail!'
    },


    nl_BE: {
      Username: 'Gebruikersnaam',
      Password: 'Wachtwoord',
      Forgot_password: 'Wachtwoord vergeten?',
      Sign_in: 'Inloggen',
      Search:'Zoeken',
      Products:'Artikelen',
      Add_Product:'Artikel toevoegen',
      Dashboard:'Dashboard',
      Sales_Order:'Verkooporder',
      Purchase_Order:'Inkooporder',
      Supplier:'Leverancier',
      Customer:'Klant',
      Product_Group:'Artikelgroep',
      Sales_Unit:'Verkoopeenheid',
      Kilogram:'Kilogram',
      Product:'Artikel',
      Productcode:'Artikelcode',
      Previous:'Vorige',
      Next:'Volgende',
      Show_entries:'Toon records',
      Show:'Toon',
      Entries:'records',
      Show_page:'Pagina weergegeven',
      Producttype: 'Producttype',
      Concentration: 'Concentratie',
      Addition: 'Toevoeging',
      Description: 'Omschrijving',
      Salesunit: 'Verkoopeenheid',
      Partial: 'Deelbaar',
      Intrastat: 'Intrastat',
      Save: 'Opslaan',
      User: 'Gebruiker',
      Add_User: 'Voeg gebruiker toe',
      FirstName: 'Voornaam',
      LastName: 'Achternaam',
      Email: 'E-mail',
      Active: 'Actief',
      State: 'Provincie',
      View_User: 'Bekijk gebruiker',
      Edit_User: 'Bewerk gebruiker',
      UserName: 'Gebruikersnaam',
      Roles: 'Rollen',
      ConfirmPassword: 'Bevestig wachtwoord',
      PhoneNumber: 'Telefoonnummer',
      IsActive: 'Is actief',
      Product_Details: 'Artikeldetails',
      Productgroup: 'Productgroep',
      Purchase_Price: 'Inkoopprijs',
      Price: 'Prijs',
      Start_date: 'Begindatum',
      End_date: 'Einddatum',
      Add_Purchase_Price: 'Voeg inkoopprijs toe',
      Sales_Price: 'Verkoopprijs',
      Add_Salese_Price: 'Voeg verkoopprijs toe',
      Transport_Price: 'Transportprijs',
      Id: 'Id',
      Transporter: 'Vervoerder',
      Pricingtype: 'Prijstype',
      Add_Transport_Price: 'Voeg transportprijs toe',
      Add_Sales_Order: 'Verkooporder toevoegen',
      Reference: 'Referentie',
      Order_Date: 'Besteldatum',
      Total_amount: 'Totaalbedrag',
      Sales_Order_Details: 'Verkooporder details',
      Loading_Date: 'Laaddatum',
      Quantity: 'Aantal',
      Amount: 'Bedrag',
      Add_Pursase_Order: 'Inkooporder toevoegen',
      Invoice: 'Factuur',
      Invoice_date: 'Factuurdatum',
      Journal: 'Dagboek',
      Expiration_Date: 'Vervaldatum',
      Purchase_Order_Details: 'Inkooporder details',
      Add_row: 'Rij toevoegen',
      GlCode: 'Grootboekrekening',
      VATCode: 'BTW code',
      VATAmount: 'BTW bedrag',
      Reporting_Date: 'Rapportage datum',
      Purchase_Unit: 'Inkoopeenheid',
      Approver: 'Goedkeurder',
      Add_Price: 'Prijs toevoegen',
      Copy_Product: 'Artikel kopiëren',
      Tasks: 'Taken',
      Add_Tasks: 'Taak toevoegen',
      Creat_Task: 'Taak aanmaken',
      Task_Type: 'Taak type',
      Employee: 'Werknemer',
      Deadline: 'Deadline',
      Subject: 'Onderwerp',
      CustomerName: 'Klantnaam',
      DateCreated: 'Datum aangemaakt',
      CreateBy: 'Aangemaakt door',
      Address: 'Adres',
      Postcode: 'Postcode',
      City: 'Stad',
      Country: 'Land',
      Action: 'Actie',
      Codex_SAS:'Coprodex SAS',
      Extra_information: 'Extra informatie',
      Financial: 'Financieel',
      Location: 'Locatie',
      Telephone: 'Telefoon',
      E_mail: 'E-mail',
      Website: 'Website',
      Turnover_current_year: 'Omzet huidig jaar',
      Turnover_last_year: 'Omzet afgelopen jaar',
      Revenue_for_the_year: 'Omzet van jaar',
      Progress: 'Voortgang',
      Payment_term: 'Betaaltermijn',
      days: 'dagen',
      Contacts: 'Contactpersonen',
      Telephone_work: 'Telefoon werk',
      Mobile: 'Mobiel',
      Status: 'Status',
      All_contacts: 'Alle contactpersonen',
      Add_contacts: 'Voeg contactpersoon toe',
      Models: 'Modellen',
      Model: 'Model',
      Type: 'Type',
      Size: 'Afmeting',
      Articles: 'Artikelen',
      Item_Type: 'Artikelsoort',
      Color: 'Kleur',
      Length: 'Lengte',
      Orders: 'Orders',
      Ordernumber: 'Ordernummer',
      Orderdate: 'Orderdatum',
      Deliverydate: 'Leverdatum',
      Customer_ordernumber: 'Klant ordernummer',
      Item: 'Artikel',
      Discount: 'Korting',
      CustomerItemNumber: 'Klant artikelnummer',
      Unit:'Eenheid',
      Number: 'Aantal',
      Order_detail: 'Order details',
      Competitor_models: 'Modellen van concurrenten',
      Revenue: 'Omzet',
      Price_agreements: 'Prijsafspraken',
      Upon_purchase: 'Bij afname',
      Price_per: 'Prijs per',
      Show_rate: 'Toon tarief',
      Rate: 'Tarief',
      Quotations: 'Offertes',
      Quotation_Number: 'Offertenummer',
      Delivery: 'Levering',
      Approved: 'Goedgekeurd',
      Date: 'Datum',
      Not_Approved: 'Niet goedgekeurd',
      Quote_detail: 'Offerte details',
      Mold: 'Matrijs',
      Article_Number: 'Artikelnummer',
      Visit_report: 'Bezoekrapport',
      Add_VisitReport: 'Bezoekrapport toevoegen',
      Create_a_new_report: 'Nieuw rapport aanmaken',
      Select_Customer: 'Selecteer klant',
      Visit_Date: 'Bezoekdatum',
      Further: 'Verder',
      existing_or_potential_customer: 'Bestaande of potentiele klant',
      Select_answer: 'Selecteer antwoord',
      Remarks: 'Opmerkingen',
      Select: 'Selecteer...',
      CreatedBy: 'Gemaakt door',
      Submit: 'Aanmaken',
      Visit_reports_page: 'Bezoekrapport pagina',
      Customers_page: 'Klanten pagina',
      Number_Of_Tasks: 'Aantal taken',
      Nearest_Customers: 'Dichtstbijzijnde klanten',
      dashboard_page_customer_near_by_km: 'Kilometer',
      map_lang: 'NL',
      Create_Customer: 'Aanmaken klant',
      Customer_City: 'Stad',
      Note: 'Notitie',
      Add_Customer: 'Toevoegen Klant',
      Create_Contact: 'Aanmaken Contact',
      Phone_Work: 'Telefoon Werk',
      Phone: 'Telefoon',
      Name: 'Naam',
      Zipcode: 'Postcode',
      Edit_Customer: 'Bewerk Klant',
      Edit_Contact: 'Bewerk Contact',
      Edit_Task: 'Bewerk Taak',
      Edit_Report: 'Bewerk bezoekrapport',
      Task_history: 'Taak geschiedenis',
      PreviousEmployee: 'Vorige medewerker',
      NewEmployee: 'Nieuwe medewerker',
      ChangeDate: 'Wijzigingsdatum',
      Top_Customers: 'Top 10 Klanten',
      Top_Items: 'Top 10 Artikelen',
      Top_Models: 'Top 10 Modellen',
      Answer_visit_report: 'Antwoorden bezoekrapport',
      Question: 'Vraag',
      Answer: 'Antwoord',
      Attachment: 'Bijlage',
      Choose_File: 'Kies bestand',
      View: 'Bekijken',
      Documents: 'Documenten',
      DocumentId: 'DocumentId',
      Task: 'Taak',
      Success: 'Succesvol!',
      Fail: 'Mislukt!'
    }
  };